### ISSUE TITLE
werkzeug.routing.BuildError: Could not build url for endpoint 'product_save' with values ['products_id']. Did you forget to specify values ['id']?

### ISSUE THREAD

**Issue by aksiaaksi** [aksiaaksi/Workplace#1]
https://github.com/aksiaaksi/Workplace/blob/1bb4f964ce2d9ade3766bd1ed11b83c989621804/app/templates/product-edit.html#L18

не получается разобраться в данной ошибке при добавлении нового товара?

**Comment by coursar** [comment]
1. Пробелов быть не должно
2. Имя в угловых скобках должно соответствовать имени аргумента
```python
    @app.route('/new-product/<products_id>/save', methods=['POST'])
    def product_save(products_id)
```
